version: '3.9'

services:
  web:
    build: .
    container_name: django
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:14.5-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  postgres_data:
